# Generated by Django 3.2.8 on 2021-10-08 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.users')),
                ('review_id', models.CharField(max_length=22)),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
                ('vote_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
