from django.contrib.auth.hashers import make_password
from django.db import models

# Create your models here.

"""
The models below were generated by Django's inspectdb utility. 
When the command 'python manage.py insepctdb' is entered into the
console, inspectdb will examine any existing tables in the database 
that is specified in settings.py and generate models for each one. 
The output will be printed in the console, where it can be be copied
and paste. Alternatively, the command 'python manage.py inspectdb > models.py' 
can be used to write the models directly into models.py.     

Link to Documentation:
https://docs.djangoproject.com/en/3.2/howto/legacy-databases/

"""


class reviews(models.Model):
    user = models.OneToOneField('Users', models.DO_NOTHING, primary_key=True)
    review_id = models.CharField(max_length=22)
    upvote = models.IntegerField()
    downvote = models.IntegerField()
    vote_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'reviews'
        unique_together = (('user', 'review_id'),)


class users(models.Model):
    username = models.CharField(max_length=50)
    email = models.CharField(max_length=256)
    password = models.CharField(db_column='pass', max_length=256)

    class Meta:
        managed = False
        db_table = 'users'
